### ISSUE TITLE
ledger manager browsers?

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/ledger-manager-chrome#1]
When will the ledger manager work with other browsers like brave,firefox and opera?

**Comment by nicoodeimos** [comment]
The first version of the app will only be supported under Chrome, but we plan to release a major update later in the year that will be accessible without the need to install and use a browser backend.

**Comment by ghost** [comment]
by chrome do you mean Chrome OS? will you release the major update(which
will independent of a browser backend) around the same timeframe as the
chrome OS ledger app?

**Comment by nicoodeimos** [comment]
Yes, the first version which is being actively developed, will be be released as a app compatible for Chrome/Chromium (the browsers) and Chrome/Chromium OS. 
The next release, available later this year will most certainly be to be independent from any Chrome backend.
Not sure what you mean by "the chrome OS ledger app"?

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monero support](https://trello.com/c/wsK0myEm/52-monero-support)
