### ISSUE TITLE
Trying to upgrade Firmware from 1.3.1 to 1.4.1

### ISSUE THREAD

**Issue by Moneybob** [LedgerHQ/ledger-manager-chrome#20]
Ledger Nano S 
I am unable to install OS updater 
Firmware Version I'm trying to install 1.4.1 
Currently on my Nano S Version 1.3.1 
I have rested the Nano S (reentered the 24 code words) 
I have removed all apps on the Nano S 
I have exited Google and restarted 
I have checked that I don't have a USB issue. 
Turned off and restarted my computer
I have latest version of Google Browser.
Running Windows 10 64 bit Tried on Windows 7 machine didn't work.

**Comment by gre** [comment]
I would recommend you contact our support team that have more resource on answering these questions. https://support.ledgerwallet.com/
Github issue are for development issues.
