### ISSUE TITLE
Le Derp

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/ledger-manager-chrome#21]
Nothing to see here. Move along.

**Comment by jhabdas** [comment]
Turns out it's not you. In fact, it's either Yandex or something in Chromium. It's intermittent so I came up with a false positive here. Sorry for the FUD.

**Comment by jhabdas** [comment]
This turns out to be an issue with social widgets on a page and a derp on my part. Sorry.

**Comment by meriadec** [comment]
:+1:
