### ISSUE TITLE
Broken link on Quick Start

### ISSUE THREAD

**Issue by alx** [LedgerHQ/ledger-manager-chrome#4]
Hi Ledger team,

I'm trying to follow the Quick Start installation from https://www.ledgerwallet.com/wallet and get the following error in js console when clicking on "Install App Manager".

To reproduce:

- open Chrome to https://www.ledgerwallet.com/wallet
- go on Ledger Nano S
- click on Install App Manager
- => Nothing happen, js ocnsole shows "Uncaught No Chrome Web Store item link found."

Expected: App Manager install process is launched

Thanks and have a nice day,

Alex

**Comment by nicoodeimos** [comment]
Thank you for your report. The issue has been fixed!
