### ISSUE TITLE
ledger nano S stuck on update

### ISSUE THREAD

**Issue by cyberpay** [LedgerHQ/ledger-manager-chrome#6]
if your update servers are overload or some glitch in existing system why dont you give users chance to wipe existing s/w from device and download/install fresh copy of OS in ledger nano s. 
it is very frustrating when a simple OS update will stuck and for hours and hours stuck on update screen without any success.

**Comment by jzargo11** [comment]
I'm in the same boat please help

**Comment by btchip** [comment]
that's a temporary network issue. Please retry later
